<?php

/**
 * @file
 * Hook implementations for Social Auth PayPal module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function social_auth_paypal_help($route_name, RouteMatchInterface $route_match) {
  $output = '';

  switch ($route_name) {
    case 'social_auth_paypal.settings_form':
      $output = '<h3>' . t('Configuration instructions') . '</h3>';
      $output .= '<p>';
      $output .= t('Configuration instructions and other useful documentation can be found at the <a href="@doc-url">Social Auth PayPal documentation</a>.',
        ['@doc-url' => 'https://www.drupal.org/docs/8/modules/social-api/social-api-2x/social-auth-2x/social-auth-paypal-2x-installation']);
      $output .= '</p>';
      break;

  }

  return $output;
}
