social_auth_paypal.settings:
  type: config_object
  label: 'Social Auth PayPal settings'
  mapping:
    client_id:
      type: string
      label: 'Client ID'
    client_secret:
      type: string
      label: 'Client Secret'
    is_sandbox:
      type: string
      label: 'Is this a sandbox?'
